### ISSUE TITLE
Unable to change the first day of the week.

### ISSUE THREAD

**Issue by Apper123** [vdesmet93/holo-calendar#3]
Unable to change the first day of the week.

I prefer the first day of the week is Sunday. 

Please add in. Thanks a lot. 
:)

**Comment by vdesmet93** [comment]
Have you tried setFirstDayOfWeek()? Works on both the CalendarView and the MultiCalendarView.

For example:
`view.setFirstDayOfWeek(Calendar.SUNDAY)`
